publiclab/community-toolbox

index.html
Hello there,
Found the issue by looking for the tag Hacktoberfest, and it looked like a nice issue to solve.
I solved it by making the options explicit in the index.html file, just like the other API calls that are done there. This increases clarity and solves the issue.
Please accept my PR.
=> Issue #6 - All Contributors Now Shown

README.md, dist/community-toolbox.js, index.html, package.json, src/community-toolbox.js, src/ui.js
=> mostly working org-wide issue listings

dist/community-toolbox.js, src/community-toolbox.js
Clicking on contributor username/avatar will now lead to their contributions to the repository.
=> Links to contributors now go to their contributions (resolves #15)

dist/community-toolbox.js, src/community-toolbox.js
| Q                                                      | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                      | Fix
| Tickets (_issues_) concerned               | #20 
---
Fix a JS error on contributors display when use `o` and `r` params of the index page
Add a condition when we get the number of page in the response of Github API since `link` param is returned **only** if we have more than **one** page (so 100 contributors in our case)
=> add conditions to check if header contain links

src/ui.js
=> fix: suffix time ago

README.md
Instructions to install page locally added
Issue #18
=> install instructions added

index.html
Fixes#35
Add Gitter chatroom link to welcome page
=> Fixes#35 Add Gitter chatroom link to welcome page

.github/config.yml
This PR solves #33 and also includes the changes mentioned by @jywarren 
Thank You!  😄
=> Change config.yml as mentioned

index.html
fixed:  https://github.com/publiclab/plots2/issues/3589
=> Add Publiclab organization link to community-toolbox website 

src/ui.js
=> Updated ui.js, resolving #58

dist/community-toolbox.js, src/community-toolbox.js, src/getAllContribsUtility.js, src/repoContributorsUtility.js
I'll be sharing a working GIF of this PR as soon as my API quota gets refilled.
=> Increase code readability of src files.

examples/embed.html
Fixes #28 
Here is the GIF...
@jywarren Please take a look
=> Add issue filter feature on embed.html

.github/first-timers-issue-template.md
Issue [link](https://github.com/publiclab/plots2/issues/3681#issuecomment-429254015)
=> Create a first timers issue template

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .github/first-timers-issue-template.md, .github/first-timers.yml
Fixes https://github.com/publiclab/plots2/issues/3685 , #71
=> Add PR, Issue,and FTO Templates

index.html, src/community-toolbox.js
=> community-toolbox.js

src/community-toolbox.js
Wraps avatars in a <a> tag with a title tag to display username on hover. Fixes #39.
* [✔️] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [✔️ ] code is in uniquely-named feature branch and has no merge conflicts
* [✔️ ] PR is descriptively titled
* [✔️ ] PR body includes `fixes #0000`-style reference to original issue #
* [✔️ ] ask `@publiclab/reviewers` for help, in a comment below
=> Add title tags to avatars to show name

index.html, src/community-toolbox.js
=> Enhancement in the spinner icon behaviour

index.html
This is a pretty simple change -- @Rishabh570 what do you think?
=> Move up "Recent Contributors" section

README.md
Fixes #72
* [x ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ x] PR is descriptively titled
* [ x] PR body includes `fixes #0000`-style reference to original issue #
* [ x] ask `@publiclab/reviewers` for help, in a comment below
=> Add instructions for filtering by labels and repo using URL

index.html
=> added proper link to readme.md

dist/community-toolbox.js, index.html, package-lock.json, src/community-toolbox.js
=> Images on recent contributors is linked to github profile

CODE_OF_CONDUCT.md
=> #128 Create CODE_OF_CONDUCT.md in Community toolbox

index.html
@jywarren This PR adds survey form temporarily to the site.
=> Add survey form temporarily

package-lock.json
Fixes #126 
@jywarren I've added new lock file, please check if it works or not. I think it should work now...
=> Add new package-lock file.

examples/demo.css, index.html
=> #80 created the scroll to top button

examples/demo.css
Fixes #166
Thanks!
Removed @media on line 37
=> Centering the images by updating demo.css

index.html
=> Add "fork me on github" ribbon Fixes #182

index.html
=> here are my changes.

examples/demo.css
=> Added styles as directed

examples/demo.css, index.html
Fixes #174 
Thanks!
(Screenshot1)
I setup fontawesome to view the icons in the footer (Screenshot2)
=> Connect with us section

dist/community-toolbox.js, src/scripts/community-toolbox.js, src/utils/getAllContribsUtility.js, src/utils/getRecentCommitsUtility.js
=> Updated list storage to IndexedDB

examples/demo.css, index.html
I'm really sorry but I couldn't figure out how to doing below tests.
In addition, in DIFF, two lines were not marked as changed not as [example](https://github.com/publiclab/community-toolbox/issues/214).
I am so sorry if I did make any mistake.
```css
- #connectwithusbody {   // this is not marked as changed
- overflow: hidden;   // this is ok
- }   // this is not marked as changed
```
---
Please be sure you've reviewed our contribution guidelines at …
=> made 'connect with us' section responsive

dist/community-toolbox.js, examples/demo.css, examples/demo.js, examples/night-mode.js, examples/themes.css, examples/themes.js, index.html, package-lock.json
=> add night mode theme.

examples/copyToClipboard.js, examples/demo.css, index.html
=> Add a copy to clipboard button

dist/community-toolbox.js, index.html, package-lock.json, package.json, src/scripts/community-toolbox.js, src/utils/contribsUtil/fetchAllRepoContribs.js, src/utils/contribsUtil/fetchRepoContribs.js, src/utils/contribsUtil/main.js, src/utils/contribsUtil/storeAllContribsInDb.js, src/utils/recentContribsUtil/fetchAllRecentMonthContribs.js, src/utils/recentContribsUtil/fetchRecentMonthContribs.js, src/utils/recentContribsUtil/getContribsLastMonth.js, src/utils/recentContribsUtil/main.js, src/utils/recentContribsUtil/storeAllRecentContribsInDb.js, src/utils/repoUtil/fetchRepoUtil.js, src/utils/staleIssuesUtil.js
=> Add notifications for user acknowledgement

examples/copyToClipboard.js, examples/demo.css, index.html
fixes #0003-style reference to original issue #240 
Thanks!
=> Update index.html, copyToClipboard.js and demo.css as Issue #240.

dist/community-toolbox.js, examples/copyToClipboard.js, examples/demo.css, examples/demo.js, examples/themes.js, index.html, src/UI/recentContributorsUI.js, src/scripts/community-toolbox.js, src/utils/filterUtil.js, src/utils/recentContribsUtil/fetchAllRecentMonthContribs.js, src/utils/recentContribsUtil/fetchRecentMonthContribs.js, src/utils/recentContribsUtil/freshFetch.js, src/utils/recentContribsUtil/getContribsLastMonth.js, src/utils/recentContribsUtil/getContribsLastWeek.js, src/utils/recentContribsUtil/main.js, src/utils/recentContribsUtil/queryTime.js, src/utils/recentContribsUtil/storeAllRecentContribsInDb.js, src/utils/recentContribsUtil/withinMonthsOrNot.js
=> Add filter for recent contributors' list

.travis.yml, README.md, package-lock.json, package.json, spec/contribsUtil/fetchAllRepoContribs.spec.js, spec/contribsUtil/fetchRepoContribs.spec.js, spec/contribsUtil/fetchRepoContribsUtil.spec.js, spec/contribsUtil/main.spec.js, spec/contribsUtil/storeAllContribsInDb.spec.js, spec/helper.js, spec/recentContribsUtil/fetchAllRecentMonthContribs.spec.js, spec/recentContribsUtil/fetchRecentMonthContribs.spec.js, spec/recentContribsUtil/freshFetch.spec.js, spec/recentContribsUtil/getContribsLastMonth.spec.js, spec/recentContribsUtil/getContribsLastWeek.spec.js, spec/recentContribsUtil/main.spec.js, spec/recentContribsUtil/queryTime.spec.js, spec/recentContribsUtil/storeAllRecentContribsInDb.spec.js, spec/recentContribsUtil/withinMonthsOrNot.spec.js, spec/recentContribsUtil/withinThisWeekOrNot.spec.js, spec/repoUtil/fetchRepoUtil.spec.js, spec/staleIssuesUtil/staleIssuesUtil.spec.js
=> Add tests for utils folder

examples/demo.css, index.html
Solved Issue #254 
Removed extraordinary line and center aligned the texts to make the UI look beautiful.
=> Footer UI changes

dist/community-toolbox.js, src/scripts/community-toolbox.js
=> Remove redundant function from community-toolbox.js #218

src/UI/issuesUI.js
=> Added author thumbnail to issue display

examples/demo.css, index.html
As this is minor UI weird behaviour I decided not to create a new issue and made this PR. Please review and let me know if it works out.
I noticed the footer elements are not being centered like so:
This PR tries to fix it by adding minor adjustments to achieve this look like so:
Thank you!
=> Fixed UI: footer elements not centered

index.html
Added it because the language attribute helps to specify the language of the element's content
Thanks!
=> Added a language attribute

index.html
=> fix header UI issue.

examples/demo.css
Before the PR : 
After the PR :  
Thanks!
=> Recent Contributor SORT Dropdown MADE RESPONSIVE

dist/community-toolbox.js, index.html, package-lock.json, spec/helper.js, spec/staleIssuesUtil/staleIssuesUtil.spec.js, src/scripts/community-toolbox.js, src/utils/staleIssuesUtil.js
=> fixed the stale issues which fixes issue #282

examples/demo.js, examples/themes.js, examples/urlHash.js, src/UI/contributorsUI.js, src/UI/issuesUI.js, src/scripts/chart.js, src/utils/contribsUtil/fetchAllRepoContribs.js, src/utils/contribsUtil/storeAllContribsInDb.js, src/utils/getRepoContributors.js
=> JS code enhancement

dist/community-toolbox.js, src/UI/contributorsUI.js
=> Fixed the hyperlink issue (Fixes issue #320)

examples/demo.css, index.html
=> Fix The Position Of Fork me Ribbon

examples/demo.css
=> Added the scrolling in-list, Fixes Issue #330

index.html
=> Add a all repositories button to dropdown

dist/community-toolbox.js, src/UI/recentContributorsUI.js
=> Show Github username over avatar in recent contributors section

examples/demo.css, index.html
=> Add gitter option in connect with us section

docs/getting_started.md
=> updated installation instructions

examples/demo.css
re https://github.com/publiclab/image-sequencer/pull/1741
=> Update demo.css to fix font links to League Spartan CDN via fontsource

src/UI/issuesUI.js
=> restyle missing avatar images as grey circles

index.html, src/UI/ftoAuthorsUI.js
This commit adds the fto authors username before the thumbnail
fixes #415
Thanks!
=> add fto authors username

.github/workflows/tests.yml
=> Created tests.yml to move to GitHub Actions

index.html
=> Dependency chart is added to the navbar

examples/demo.css, index.html
=> Formate of web page is fixed

index.html
=> Language section is added into the navbar

index.html
Updated recent contributors list and heading
fixes #460 - Add permalink to Recent Contributors section
=> Added permalink to Recent Contributors section

index.html
=> moved link tags to the head. this fixes #550

examples/embed.html, index.html
=> Fix charset character encoding value in embed and index file. Fixes #548

examples/demo.css, index.html
=> Remove inline styling and update demo.css

index.html
=> Add bootstrap classes

examples/demo.css, index.html
The first commit fixes: #564,
Thanks!
=> fixes: #564 Grouped similar inline style rule into demo.css

config.json, index.html, src/scripts/configure.js
Fixes #568 - Also put all changes from PRs https://github.com/publiclab/community-toolbox/pull/572, https://github.com/publiclab/community-toolbox/pull/573, https://github.com/publiclab/community-toolbox/pull/574 together into one PR.
=> (fix): Update broken links in index.html page
